### ISSUE TITLE
Clearing a graphics object with D2DColor.Transparent?

### ISSUE THREAD

**Issue by ItsEddie** [jingwood/d2dlib#2]
Hey man,

It's me again! You know how yesterday you've shown me in the fantastic example that in order to draw like a layer I need to call `Graphics.BeginRender(D2DColor.Transparent)`?

Well, today I figured out I also need to clear the layer, as in, what happens when you call `Graphics.BeginRender(D2DColor.Red)`, but then with the transparent color.

Is this possible to do without re-creating the graphics object? If so, 'd love to know how!

Regards!

**Comment by jingwood** [comment]
Hi! Glad to hear that you like it. Now a new `Clear` method has been added, by adding this there is some changes to the API, please see #3 

You may also change the csharp wrapper code to match the API changes, refer to here
https://github.com/jingwood/d2dlib/commit/598ef18ed2f360691e1623c62b23dae05823ede6#diff-e891fb22e9ebc94ace791db647087810L31

and here
https://github.com/jingwood/d2dlib/commit/598ef18ed2f360691e1623c62b23dae05823ede6#diff-fb2d102514f7fdd9598ab88bd4327ab6L94

**Comment by ItsEddie** [comment]
Perfect!

**Comment by ItsEddie** [comment]
Oh - different question. You know how you said we couldn't render to a Bitmap because it isn't the correct handle, does this mean it's entirely out of bounds to render anything to a bitmap? So say, we can actually export what's being drawn as an image?

**Comment by jingwood** [comment]
Usually the bitmap we used in Windows Form is GDI+ based bitmap, that's data is stored in motherboard memory (CPU memory), while the Direct2D based bitmap is stored in GPU memory. That's why we can get hardware accelerated high drawing performance. 

But since this reason we cannot get the content of a Direct2D bitmap frequently (in fact we can), every time we doing this will cause a memory copy between the CPU memory and GPU memory, this is an expensive operation and we need to avoid  doing it as possible as we can, this usually decides how we design our application.

The HBITMAP (handle of a bitmap) of a Windows Form bitmap, is point to a memory address in CPU memory, so that's why we can't create a Direct2D graphics context from it directly in GPU memory. 

Alternative way is to create an empty Direct2D graphics context, and call its `DrawBitmap` method to draw a GDI+ bitmap, drawing operation actually will copy the data of GDI+ bitmap from CPU memory to GPU memory. Since doing this in every rendering frame is expensive, if your bitmap is static, usually we can firstly  create a Direct2D bitmap by calling the device method `CreateBitmapFromGDIBitmap`, this method will copy the data between CPU and GPU memory, and draw this `D2DBitmap` in every frame.

So based this let's talk about what are you want to do?

**Comment by ItsEddie** [comment]
What I'm hoping to do is to export a `D2DBitmapGraphics` as an image file (bitmap, jpeg, it's kind of irrelevant at the moment), or at least convert it to an image. 

The problem is however, that in my Drawing Control I have multiple instances of **D2DBitmapGraphics**, all of which have to be drawn on the same bitmap in order to draw the full picture.

Imagine that one `D2DBitmapGraphics` contains a tree, and another the tree's apples, I'd want to be able to export the apple `D2DBitmapGraphics` **and** the tree, or just the apples individually.

Just basically saving as an image so I can work on it later.

Speaking of which, since you've resolved the issues regarding clearing using the transparency color, does this mean it's also now possible to draw lines using a transparent color in order to erase lines (an eraser tool, that is.)

I hope I'm making sense. Currently I'm unable to save what's drawn to the screen.

**Comment by jingwood** [comment]
OK got it, let me finished the API change in order to get data back from a Direct2D bitmap.

By the way, a few years ago I made another software that can take screen snapshots and adding arrows or rectangles on the snapshots. The software doesn't use this d2dlib, you can check it out at: https://github.com/unvell/JustCapture

**Comment by jingwood** [comment]
Pressed on wrong button 'close and comment'

**Comment by ItsEddie** [comment]
Thanks a lot for your continued help. Also: That's a really nice looking app you created there. It looks a lot like mine. Maybe at some point we could combine our software - would sure be interesting.

**Comment by ItsEddie** [comment]
Any luck so far updating the API?

**Comment by jingwood** [comment]
No problems! Still working on this.

**Comment by jingwood** [comment]
Hi Eddie,

I have did some research on this, but finally I think I can't make an API that read back data from a Direct2D device bitmap, I think these articles explain why I can't. 

https://stackoverflow.com/questions/9021244/how-to-work-with-pixels-using-direct2d
https://stackoverflow.com/questions/23686096/how-to-get-pixels-from-window-using-direct2d

Even by using some methods can achieve the feature but like the article above says, that won't get any benefits from Direct2D hardware accelerated.

For your case I think you can keep a normal Windows Form Bitmap (rather than Direct2D bitmap) for every layers and draw the combined bitmap on screen, so you can save every layer individually.

regards, Jingwood

**Comment by ItsEddie** [comment]
`draw the combined bitmap on screen`

I'm assuming you mean by using your library right? Because before I got here I was doing that and `Graphics` is just too slow to render big bitmaps.

**Comment by jingwood** [comment]
@ItsEddie 

Finally I got finished the API and now it works good to me.

https://github.com/jingwood/d2dlib/raw/master/snapshots/bitmap_rendering.png
I think this is so close to your case, the source code can be found here: 
https://github.com/jingwood/d2dlib/blob/master/src/Examples/Demos/BitmapCustomDraw.cs

But since so many interface has been changed you may have to copy the following files to your application again.
- D2DEnums.cs
- D2DLib.cs
- D2DStructs.cs

And I have added more examples to show how to use this library, hope it helps you.
https://github.com/jingwood/d2dlib

**Comment by ItsEddie** [comment]
Oh my god you're so amazing! Thanks a lot!
