### ISSUE TITLE
Render YUV image

### ISSUE THREAD

**Issue by digibum** [jingwood/d2dlib#83]
I'm new to Direct2D World and don't quite understand how to prepare images to be used in D2DLib.
My images come from DVR Recorder and are in YUV format. How would one process images that are not in Bitmap form to be used in D2DLib? The most important thing is speed, since conversion from YUV to RGB is painfully slow on CPU side.
Thank you!

**Comment by jingwood** [comment]
Maybe you have to provide more details to get help. How do you handle your image in memory? What type of image that read from the DVR Recorder? What API or library you are using?

If you are using something like DirectWrite, which is a part of Direct2D so integrations in some level with this library can be implemented. 

As you said the converting between Bitmap is expensive. I think the good plan is to making the images can be processed in GPU side in order to build a smooth process pipeline.

**Comment by jingwood** [comment]
Close this issue, if you still have problem please reopen or create a new.
